using System.IO;

namespace TypeD.Code
{
    /// <summary>
    /// Represents an abstract base class for generating and managing TypeD-specific code files.
    /// </summary>
    /// <remarks>This class extends the <see cref="Codalyzer"/> base class and provides functionality for
    /// handling TypeD-specific code generation, initialization, and file management. It includes methods for
    /// initializing TypeD classes, generating code, and saving the resulting files. Derived classes must implement the
    /// <see cref="InitTypeDClass"/> method to define TypeD-specific initialization logic.</remarks>
    public abstract class TypeDCodalyzer : Codalyzer
    {
        // Properties
        /// <summary>
        /// Gets or sets the TypeD file associated with the current instance.
        /// </summary>
        protected CodeFile TypeDFile { get; set; }

        // Constructors
        /// <summary>
        /// Initializes a new instance of the <see cref="TypeDCodalyzer"/> class.
        /// </summary>
        /// <remarks>This constructor initializes the <see cref="TypeDCodalyzer"/> instance with default
        /// settings. The <see cref="Codalyzer.PartialClass"/> property is set to <see langword="true"/>, and the <see cref="TypeDFile"/>
        /// property is initialized as a new <see cref="Codalyzer.CodeFile"/> instance with its
        /// <see cref="Codalyzer.CodeFile.AutoGeneratedFile"/> property set to <see langword="true"/>.</remarks>
        public TypeDCodalyzer() : base()
        {
            PartialClass = true;
            TypeDFile = new CodeFile
            {
                AutoGeneratedFile = true
            };
        }

        /// <summary>
        /// Initializes the current instance by setting up the target file, initializing the TypeD class, and
        /// configuring the file path for TypeD operations.
        /// </summary>
        /// <remarks>This method overrides the base implementation to perform additional setup specific to
        /// TypeD. It configures the <see cref="Codalyzer.CodeWriter.TargetFile"/> and initializes the TypeD class before invoking
        /// the base initialization logic.</remarks>
        public override void Init()
        {
            Writer.TargetFile = TypeDFile;
            InitTypeDClass();
            TypeDFile.FilePath = FilePathTypeD();
            base.Init();
        }

        /// <summary>
        /// Initializes the Type D class with the necessary setup or configuration.
        /// </summary>
        /// <remarks>This method must be implemented by derived classes to provide the specific
        /// initialization logic required for the TypeD class. It is called as part of the class's lifecycle and should
        /// ensure that the class is in a valid state for use.</remarks>
        protected abstract void InitTypeDClass();

        // Functions
        /// <summary>
        /// Generates the output file for the specified type definition.
        /// </summary>
        /// <remarks>This method sets the target file for the writer to the type definition file and
        /// writes the file content. It overrides the base implementation to provide specific functionality for type
        /// definition generation.</remarks>
        public override void Generate()
        {
            base.Generate();

            Writer.TargetFile = TypeDFile;
            WriteFile();
        }

        /// <summary>
        /// Saves the current state of the object to a file.
        /// </summary>
        /// <remarks>If the file is not auto-generated and already exists at the specified path, the save
        /// operation is skipped. Otherwise, the file is saved using the <see cref="TypeDCodalyzer.Save"/> method.</remarks>
        public override void Save()
        {
            base.Save();

            if (!TypeDFile.AutoGeneratedFile && File.Exists(FilePathTypeD()))
            {
                return;
            }

            TypeDFile.Save();
        }

        /// <summary>
        /// Generates the file path for a type definition file based on the project structure and class details.
        /// </summary>
        /// <returns>A string representing the full file path for the type definition file. The path is constructed using the
        /// project component code path, the namespace (with dots replaced by double backslashes), and the class name
        /// with a ".typed.cs" extension.</returns>
        public string FilePathTypeD()
        {
            return Path.Combine(Project.ProjectComponentCodePath, Namespace.Replace(".", @"\\"), $"{ClassName}.typed.cs");
        }
    }
}
